security:
    encoders:
        App\Entity\User:
            algorithm: auto
         

    providers:
        my_provider:
            entity: 
                class: App\Entity\User 
                property: email
            

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|build|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true

            form_login:
                login_path: login
                check_path: login
                provider: my_provider
                default_target_path: getForms
               
               
                
            logout:
                path: logout
                target: login

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true
                remember_me_parameter: _remember_me
                domain: ~

    access_control:
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/profile', roles: [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_REMEMBERED] }